config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

  get 'reports/', to: 'reports#list'
  get 'reports/:project/', to: 'reports#show'
  get 'reports/:project/*path', to: 'reports#show'
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reports
  
  before_save { email.downcase! }
  validates :username,  presence: true, length: { maximum: 50 }
  validates :email, 
    presence: true, 
    length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: { case_sensitive: false }
  after_create :generate_authentication_token!
  validates :password, length: { minimum: 15 }


  has_secure_password

  private
  # Generate a session token
  def generate_authentication_token!
    self.authentication_token = Digest::SHA1.hexdigest("#{Time.now}-#{self.id}-#{self.updated_at}")
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include WardenHelper
end

app/controllers/concerns/warden_helper.rb
module WardenHelper
  extend ActiveSupport::Concern

  included do
    helper_method :warden, :log_in?, :current_user

    # prepend_before_action :authenticate!
  end

  def log_in user
    warden.set_user user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out!
    warden.logout
    warden.clear_strategies_cache!
  end

  def current_user
    warden.user
  end

  def check_user id
    if current_user[:id].to_s != id
      throw(:warden)
    end
  end

  def warden
    request.env['warden']
  end

  def authenticate!
    warden.authenticate!
  end

  def unauthorised
    throw(:warden)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :verify_authenticity_token


  before_action :authenticate!, only: [:list, :show]

# protect_from_forgery :except => [:link]

  # def show
  #   # render plain: params[:project].inspect
  #   redirect_to("/#{params[:project]}/#{params[:file]}")
  # end

  def list
    @reports = User.find(current_user[:id]).reports
  end

  def show
    # render plain: params[:path].inspect



    ## Ensure user is logged in
    if User.find(current_user[:id]).reports.find_by_name(params[:project]).nil?
    	if request.referer.nil?
    		throw(:warden)
    	else
	      previous_path = URI(request.referer).path
	      if previous_path.start_with?('/reports')
	      	redirect_to "#{previous_path}#{request.fullpath.sub("/reports", "")}"
	  	  else
	        throw(:warden)
	      end
	    end
    else

	    # if params[:path].nil?
	      filename = "reports/#{params[:project]}/index.html"
	    # else

    		filename = "reports/#{params[:project]}/#{params[:path]}"
    		filename = "#{filename}.#{params[:format]}" unless params[:format].nil?

		    filename = "#{filename}/index.html" unless File.file?(filename)
	    # end

	      render :file => "#{filename}",
	        layout: false
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    log_out!
    redirect_to "/"
  end

end

app/controllers/unauthorised_controller.rb
class UnauthorisedController < ActionController::Metal
  def self.call(env)
    @respond ||= action(:respond)
    @respond.call(env)
  end

  def respond
    self.response_body = "Unauthorised Action"
    self.status = :unauthorised
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include WardenHelper

  before_action :authenticate!, only: [:index, :show]

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    check_user params[:id]
    @user = User.find(params[:id])
    @reports = User.find(current_user[:id]).reports
  end

  def new
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/unauthorised_helper.rb
module UnauthorisedHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fileserver</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/list.html.erb
<%if !!@reports.length%>
  <%@reports.each do |report| %>
    <%=link_to "#{report.name}", report_path(report.name)%>
  <%end%>
<%else%>
<b> No reports available!</b>
<%end%>

app/views/users/new.html.erb
    <%= form_for(@user, url: signup_path) do |f| %>
      <%# = render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

app/views/users/show.html.erb
<%= link_to "Sign out", logout_path, method: :delete %>
<br>
User:
<%= @user.username %><br>
Email: <%= @user.email %> <br>
<% @reports.each do |report| %>
<%= link_to "#{report[:name]}", report_path(report[:name])%>

<% end %>